#!/bin/bash
# This script creates the firebase-init.js file from environment variables

cat << EOF > firebase-init.js
// This file is generated by a build script. Do not edit directly.

// Firebase Configuration
const firebaseConfig = {
  apiKey: "${VITE_API_KEY}",
  authDomain: "${VITE_AUTH_DOMAIN}",
  projectId: "${VITE_PROJECT_ID}",
  storageBucket: "${VITE_STORAGE_BUCKET}",
  messagingSenderId: "${VITE_MESSAGING_SENDER_ID}",
  appId: "${VITE_APP_ID}"
};

// EmailJS Configuration
const emailjsConfig = {
  serviceID: "${VITE_EMAILJS_SERVICE_ID}",
  templateID: "${VITE_EMAILJS_TEMPLATE_ID}",
  publicKey: "${VITE_EMAILJS_PUBLIC_KEY}"
};

// Initialize Firebase
firebase.initializeApp(firebaseConfig);

// Make services globally available for script.js
const auth = firebase.auth();
const db = firebase.firestore();
EOF
