#!/bin/bash
# This script creates the firebase-init.js file from environment variables

cat << EOF > firebase-init.js
// This file is generated by a build script. Do not edit directly.
const firebaseConfig = {
  apiKey: "${VITE_API_KEY}",
  authDomain: "${VITE_AUTH_DOMAIN}",
  projectId: "${VITE_PROJECT_ID}",
  storageBucket: "${VITE_STORAGE_BUCKET}",
  messagingSenderId: "${VITE_MESSAGING_SENDER_ID}",
  appId: "${VITE_APP_ID}"
};

// Initialize Firebase using the legacy/compat library
firebase.initializeApp(firebaseConfig);

// Make auth and firestore services globally available
const auth = firebase.auth();
const db = firebase.firestore();
EOF